version: '3'
services:
  app:
    container_name: portfolio-site-mlh
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/Portfolio-Site-MLH
    depends_on:
      - mysql

  mysql:
    container_name: mysql_db
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
